/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Hello;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BootControllerApi
 */
@Ignore
public class BootControllerApiTest {

    private final BootControllerApi api = new BootControllerApi();

    
    /**
     * getHello
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getHelloUsingGETTest() throws ApiException {
        Hello response = api.getHelloUsingGET();

        // TODO: test validations
    }
    
    /**
     * searchByName
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchByNameUsingGETTest() throws ApiException {
        String name = null;
        List<Hello> response = api.searchByNameUsingGET(name);

        // TODO: test validations
    }
    
}
